name: "Ubuntu 22.04 LTS"

on:
  workflow_dispatch:

jobs:
  ubuntu-2004:
    name: Test Ubuntu 22.04 LTS
    runs-on: ubuntu-22.04
    steps:

      # git clone
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      # Test commands
      - name: Run postinstall.sh 🐧
        run: sudo -E bash postinstall.sh

      # Run tests
      - name: Log 📜
        run: cat /tmp/install_*
      - name: Test 🛠️
        run: grep "CI detected" < /tmp/install_*